export const images = [
  {
    id: 1,
    img: require("./../assets/image1.png"),
  },
  {
    id: 2,
    img: require("./../assets/image3.png"),
  },
  {
    id: 3,
    img: require("./../assets/image2.png"),
  },
];

export const brandsLogo = [
  {
    id: 1,
    logo: require("./../assets/khaadi.png"),
    url: "https://pk.khaadi.com/",
  },
  {
    id: 2,
    logo: require("./../assets/ideas.png"),
    url: "https://www.gulahmedshop.com/unstitched-fabric/lawn-collection?gclid=CjwKCAjwxNW2BhAkEiwA24Cm9JViskuAMhyzKT-8JscwxCLV3JijHC6eCYb5iBDY-jv9ZGBxtsdmuBoCaKwQAvD_BwE",
  },
  {
    id: 3,
    logo: require("./../assets/j..png"),
    url: "https://www.junaidjamshed.com/",
  },
  {
    id: 4,
    logo: require("./../assets/ga.png"),
    url: "https://www.gulahmedshop.com/",
  },
];

export const productData = [
  {
    id: 1,
    img: require("./../assets/headphone.png"),
    name: "Headphones",
    price: "Rs. 3,490",
    discount: "-25%",
    rating: "4.8(210)",
    sold: "10.2k sold",
  },
  {
    id: 2,
    img: require("./../assets/lipstick.png"),
    name: "Lipstick",
    price: "Rs. 1,450",
    discount: "-50%",
    rating: "4.6(127)",
    sold: "2k sold",
  },
  {
    id: 3,
    img: require("./../assets/serum.png"),
    name: "Brightening Serum - Nirvana Botanics",
    price: "Rs. 1,890",
    discount: "-40%",
    rating: "4.1(263)",
    sold: "5.2 sold",
  },
  {
    id: 4,
    img: require("./../assets/bottles.png"),
    name: "Bottles",
    price: "Rs. 2,500",
    discount: "-70%",
    rating: "4.3(310)",
    sold: "3k sold",
  },
  {
    id: 5,
    img: require("./../assets/powder.png"),
    name: "Powder",
    price: "Rs. 2,790",
    discount: "-20%",
    rating: "4.8(250)",
    sold: "5k sold",
  },
  {
    id: 6,
    img: require("./../assets/blush.png"),
    name: "Pixi Blush on",
    price: "Rs. 2,499",
    discount: "-19%",
    rating: "4.8(350)",
    sold: " 9.1k sold",
  },
  {
    id: 7,
    img: require("./../assets/watch.png"),
    name: "Watch",
    price: "Rs. 1,990",
    discount: "-25%",
    rating: "4.7(150)",
    sold: "4k sold",
  },
  {
    id: 8,

    img: require("./../assets/glasses.png"),
    name: "Glasses",
    price: "Rs. 2,990",
    discount: "-10%",
    rating: "4.2(200)",
    sold: "1k sold",
  },
  {
    id: 9,
    img: require("./../assets/bag.png"),
    name: "Bag",
    price: "Rs. 1,250",
    discount: "-45%",
    rating: "4.5(180)",
    sold: "6k sold",
  },
  {
    id: 10,
    img: require("./../assets/mascara.png"),
    name: "Mascara",
    price: "Rs. 2,490",
    discount: "-15%",
    rating: "4.4(220)",
    sold: "6.7 sold",
  },
  {
    id: 11,
    img: require("./../assets/lotion.png"),
    name: "Nivea Body Lotion",
    price: "Rs. 1,490",
    discount: "-80%",
    rating: "4.2(100)",
    sold: "2k sold",
  },
  {
    id: 12,
    img: require("./../assets/bundle.png"),
    name: "Bundle of 4 Face Washes",
    price: "Rs. 2,390",
    discount: "-65%",
    rating: "4.8(310)",
    sold: "3.9k sold",
  },

  {
    id: 13,
    img: require("./../assets/shirt.png"),
    name: "Shirt",
    price: "Rs. 1,860",
    discount: "-40%",
    rating: "4.1(190)",
    sold: "900 sold",
  },
  {
    id: 14,
    img: require("./../assets/Shoe.png"),
    name: "Latest Trendycasual sneaker",
    price: "Rs. 2,490",
    discount: "-25%",
    rating: "4.5(230)",
    sold: "5k sold",
  },
];
export const icons = [
  { name: "home-outline", activeName: "home-sharp", route: "Dashboard" },
  { name: "search-outline", activeName: "search-sharp", route: "Search" },
  { name: "heart-outline", activeName: "heart-sharp", route: "Fav" },
  { name: "cart-outline", activeName: "cart-sharp", route: "Cart" },
];
